"""
Audit Log Pydantic schemas.
Defines request/response models for Audit Log API endpoints.
Separates API contracts from database models for better flexibility.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from sqlmodel import Field, SQLModel


class AuditLogType(str, Enum):
    """Enumeration of audit log types."""

    # Leave management
    LEAVE_REQUEST = "leave_request"
    LEAVE_APPROVAL = "leave_approval"

    # Attendance
    ATTENDANCE = "attendance"

    # Payroll
    PAYROLL = "payroll"

    # Employee management
    EMPLOYEE_UPDATE = "employee_update"
    EMPLOYEE_CREATE = "employee_create"
    EMPLOYEE_DELETE = "employee_delete"

    # Policy management
    POLICY_UPDATE = "policy_update"
    POLICY_CREATE = "policy_create"
    POLICY_DELETE = "policy_delete"

    # Document management
    DOCUMENT_UPLOAD = "document_upload"
    DOCUMENT_DELETE = "document_delete"

    # Access control
    ROLE_ASSIGNMENT = "role_assignment"
    PERMISSION_CHANGE = "permission_change"

    # Authentication
    LOGIN = "login"
    LOGOUT = "logout"

    # Data operations
    EXPORT = "export"
    IMPORT = "import"

    # User management (alias for compatibility)
    USER_MANAGEMENT = "user_management"
    EMPLOYEE_MANAGEMENT = "employee_management"

    # System/Other
    SYSTEM = "system"
    OTHER = "other"


class AuditLogBase(SQLModel):
    """
    Base audit log schema with shared fields.
    Used as foundation for other audit log schemas.
    """

    user_id: str = Field(max_length=255)
    action: str = Field(max_length=255)
    log_type: AuditLogType
    entity_type: str = Field(max_length=255)
    entity_id: str = Field(max_length=255)
    service_name: str = Field(max_length=255)
    status: str = Field(default="success", max_length=50)
    description: Optional[str] = None


class AuditLogCreate(AuditLogBase):
    """
    Schema for creating a new audit log.
    """

    old_values: Optional[str] = None
    new_values: Optional[str] = None
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None
    request_id: Optional[str] = None
    error_message: Optional[str] = None


class AuditLogUpdate(SQLModel):
    """
    Schema for updating an existing audit log.
    All fields are optional to support partial updates.
    """

    user_id: Optional[str] = Field(default=None, max_length=255)
    action: Optional[str] = Field(default=None, max_length=255)
    log_type: Optional[AuditLogType] = None
    entity_type: Optional[str] = Field(default=None, max_length=255)
    entity_id: Optional[str] = Field(default=None, max_length=255)
    old_values: Optional[str] = None
    new_values: Optional[str] = None
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None
    service_name: Optional[str] = Field(default=None, max_length=255)
    request_id: Optional[str] = None
    status: Optional[str] = Field(default=None, max_length=50)
    error_message: Optional[str] = None
    description: Optional[str] = None


class AuditLogPublic(AuditLogBase):
    """
    Schema for audit log responses.
    Includes the id field and timestamp that's generated by the database.
    """

    id: int
    timestamp: datetime
    old_values: Optional[str] = None
    new_values: Optional[str] = None
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None
    request_id: Optional[str] = None
    error_message: Optional[str] = None


class AuditLogListPublic(SQLModel):
    """
    Schema for paginated audit log list responses.
    """

    total: int
    items: list[AuditLogPublic]
    limit: int
    offset: int


class AuditLogFilter(SQLModel):
    """
    Schema for filtering audit logs.
    Used for advanced search and filtering operations.
    """

    user_id: Optional[str] = Field(default=None)
    log_type: Optional[AuditLogType] = Field(default=None)
    entity_type: Optional[str] = Field(default=None)
    entity_id: Optional[str] = Field(default=None)
    service_name: Optional[str] = Field(default=None)
    status: Optional[str] = Field(default=None)
    start_date: Optional[datetime] = Field(default=None)
    end_date: Optional[datetime] = Field(default=None)
    offset: int = Field(default=0, ge=0)
    limit: int = Field(default=100, ge=1, le=1000)
